repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: safe_house/
        args:
          - --line-length=100

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
    - id: ruff
      exclude: safe_house/
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    - id: mypy
      exclude: safe_house/
      args:
        - "--disable-error-code=import-untyped"
        - "--disable-error-code=import-not-found"
        - "--check-untyped-defs"
