download:
  min_scroll_length: 500
  max_scroll_length: 1000
  min_scroll_step: 50
  max_scroll_step: 250
  rate_limit: 400
  download_dir: "download"

paths:
  profile: "chrome_profile_dev"
  album_log: "downloaded_albums.txt"
  log_dir: "./v2ph"

chrome:
  paths:
    Linux: "/usr/bin/google-chrome"
    Darwin: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    Windows: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
